version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
        environment:
          DB_HOST: 127.0.0.1
      - image: circleci/mysql:5.6
    steps:
      - checkout
      - restore_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path vendor/bundle

      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run: bundle exec rails db:create db:migrate RAILS_ENV=test
      - run: bundle exec rspec
      - store_artifacts:
          path: coverage