version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
        environment:
          DB_HOST: 127.0.0.1
      - image: circleci/mysql:5.6
    steps:
      - checkout
      - run: cp config/database.yml
      - restore_cache:
        keys:
          # - gem-cache-v1-{{linux amd64}}-{{master}}-{{ checksum "Gemfile.lock" }}
          # - gem-cache-v1-{{linux amd64}}-{{master}}
          # - gem-cache-v1
          - gem-cache-v1-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path vendor/bundle

      - save_cache:
      #   keys: gem-cache-v1-{{linux amd64}}-{{master}}-{{ checksum "Gemfile.lock" }}
        keys: gem-cache-v1-{{ checksum "Gemfile.lock" }}
        paths:
          vender/bundle

      - run: bundle exec rails db:create db:migrate RAILS_ENV=test
      - run: bundle exec rspec