version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
        environment:
          DB_HOST: 127.0.0.1
      - image: circleci/mysql:5.6
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rails db:create db:migrate RAILS_ENV=test
      - run: bundle exec rspec